language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: py.test

#
# Then repo is configured on Travis CI to build pull requests and Branches
# As for branches though, we only want Master to build (after a merge of a PR)
#
branches:
  only:
    - master

#if !TRAVIS_PULL_REQUEST && TRAVIS_BRANCH = 'master'
addons:
  artifacts: true
  s3_region: "us-west-2"
